
#pragma config(Motor, port4, clawServo, tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//
// claw test
task main()
{
//for(int i = 0; i < 10; i++){
// motor[clawServo] = i;
// wait1Msec(10);
//}
wait1Msec(1000);
motor[clawServo] = -75;
// -75 holds a can
wait1Msec(2000);
}
