#pragma config(Sensor, in1, light, sensorReflection)
#pragma config(Sensor, dgtl10, sonar, sensorSONAR_cm)
#pragma config(Motor, port2, leftMotor, tmotorServoContinuousRotation, openLoop,
driveLeft)
#pragma config(Motor, port3, rightMotor, tmotorServoContinuousRotation, openLoop,
driveRight)
#pragma config(Motor, port4, lightSensor, tmotorServoStandard, openLoop)
#pragma config(Motor, port5, SonarServo, tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//
// scan the wall
void servoScan(){
int i;
int c = 0;
// array to hold the sonar data from each point in the sweep, each index says which way that
the sonar was pointing
// going to need to aim for the highest distance away
float arr[60];
for(i = -60; i < 60; i = i+2){
motor[SonarServo] = 2*i;
wait1Msec(50);
arr[c] = SensorValue(sonar);
c = c + 1;
}
writeDebugStream("%d",arr[0]);
}
// find and follow the longest path found after a few circles
void deepLaneScan(){
//scan around in a circle 4 times
int largestValSoFar = 25; //test value
int i;
int newValue;
for(i = 0; i < 36; i++){
writeDebugStream("HI");
// circle right storing highest sonar values
motor[leftMotor] = -55;
motor[rightMotor] = 53;
// run for 1 second
wait10Msec(100);
motor[leftMotor] = 0;
motor[rightMotor] = 0;

Arthur Hernandez
Tuesday October 19th
Autonomous Robotics

wait1Msec(10);
newValue = SensorValue(sonar);
if(newValue > largestValSoFar){
largestValSoFar = newValue;
}
}
// same thing as the prior loop but react when a high value is found
for(i = 0; i < 36; i++){
motor[leftMotor] = -55;
motor[rightMotor] = 53;
// run for 1 second
wait10Msec(1);
motor[leftMotor] = 0;
motor[rightMotor] = 0;
//wait1Msec(10);
newValue = SensorValue(sonar);
if(newValue >= largestValSoFar - 5){
scanLight();
moveForward();
scanLight();
break;
}
}
}
task main(){
deepLaneScan();
}
