
#pragma config(Sensor, dgtl10, shoulderLimit, sensorTouch)
#pragma config(Sensor, dgtl11, shoulderEncoder, sensorQuadEncoder)
#pragma config(Motor, port2, shoulderM, tmotorServoContinuousRotation,
openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//
//global variables
// shoulder limits
int sUpperBound = -30;
int sLowerBound = 30;
// currently we have one gear train and a bicep, one motor and
// shoulder motor positive is up, negative is down.
// integer function that takes the quad encoder location and spits out if the shoulder arm is
within bounds
int outOfBounds(int location){
if(SensorValue(shoulderLimit)){
return(2);
}
if(location < sUpperBound){
return(1);
}
if(location > sLowerBound){
return(2);
}
return(0);
}
// test to see if the system works by moving between the extremes of motion
void testLoop(){
int shoulderEVal = SensorValue(shoulderEncoder);
motor[shoulderM] = 20;
while(true){
if(SensorValue(shoulderLimit)){
motor[shoulderM] = 20;
}
shoulderEVal = SensorValue(shoulderEncoder);
if(outOfBounds(shoulderEVal) == 2){
motor[shoulderM] = 20;
}
else if(outOfBounds(shoulderEVal) == 1){
motor[shoulderM] = -20;
}
}
}
task main()

{
// log locations and run test
writeDebugStream("%d\n",SensorValue(shoulderEncoder));
testLoop();
}
